package tops.a288

import java.util.Vector

fun main()
{
    var v1 = Vector<String>(5)
    v1.add("r")
    v1.add("q")
    v1.add("r")
    v1.add("q")
    v1.add("q")
    v1.add("q")
    v1.add("r")
    v1.add("q")
    v1.add("q")
    v1.add("q")
    v1.add("q")
    v1.add("r")
    v1.add("q")
    v1.add("r")
    v1.add("q")
    v1.add("q")
    v1.add("q")
    v1.add("r")
    v1.add("q")
    v1.add("q")
    v1.add("q")
    v1.add("q")
    v1.add("r")
    v1.add("q")
    v1.add("r")
    v1.add("q")
    v1.add("q")
    v1.add("q")
    v1.add("r")
    v1.add("q")
    v1.add("q")
    v1.add("q")
    v1.add("q")

    println(v1.size)
    println(v1.capacity())
    println(v1.contains("q"))
    println(v1.firstElement())
    println(v1.lastElement())
    //println(v1.)
}